### ISSUE TITLE
Cannot declare class Henhed\Piwik\Helper\Tracker

### ISSUE THREAD

**Issue by iw0der** [fnogatz/magento2-matomo#1]
Hi,
I think this is a trivial problem but can not find a way out of this ...

`bash-4.2$ bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 74.8 MiBPHP Fatal error:  Cannot declare class Henhed\Piwik\Helper\Tracker because the name is already in use in /www/app/code/Henhed/Piwik/Helper/Tracker.php on line 32
b`

I deleted a lot of things (static content, cache, etc.) but keep getting this error message :-(

Thx,
A.

**Comment by henkelund** [comment]
Hi iw0der,

`php bin/magento setup:di:compile` works fine for me. At least after I run `rm -rf var/cache/* var/di/* var/generation/* var/page_cache/*` and `rmdir var/di`.

What's your Magento and PHP version? Also did you install the module with composer or with the zip archive? Or accidentally both?

/ H

**Comment by iw0der** [comment]
No way! 
Actually I had already done, but to be sure I did again as directed by you ... same result :-(

What am I using?

Distro: CentOS7
Arch:  x86_64
Magento: 2.0.2
Apache: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.5.32 mysqlnd 5.0.11-dev - 20120503
MySQL: Ver 5.6.29

I've installed from the archive, but you make me doubt that it remained some traces of a previous installation that I may have done, the other week, via composer; What can I check and remove if necessary?

Thx,
A.

**Comment by henkelund** [comment]
I could recreate the error by using PHP 5.6. Not sure why it worked with PHP 7.

I've pushed a fix to the branch [1.0.1](https://github.com/henkelund/magento2-henhed-piwik/tree/1.0.1). You can try it out by removing the module and then installing it using composer:

``` sh
composer config repositories.henhedpiwik git https://github.com/henkelund/magento2-henhed-piwik.git
composer require henhed/module-piwik:1.0.1.x-dev
```

Please let me know if that works for you and I'll publish a new release.

**Comment by iw0der** [comment]
Well done! ;-)

`bash-4.2$ bin/magento setup:di:compile`
`Compilation was started.`
`Interception cache generation... 7/7 [============================] 100% 5 mins 382.2 MiB`
`Generated code and dependency injection configuration successfully.`

Thanks,
A.

**Comment by henkelund** [comment]
Sweet, thanks for reporting the issue.
