### ISSUE TITLE
Sign In doesn't set the User ID

### ISSUE THREAD

**Issue by souzavitor** [fnogatz/magento2-matomo#10]
The User id is not being set in sign in and sign up.

**Comment by henkelund** [comment]
I'll look into it when I get some time to spare

**Comment by henkelund** [comment]
Iv'e made a branch called `user-id` that you're welcome to try out. If you're using composer you can require it with `composer require henhed/module-piwik:dev-user-id`. To start tracking the user ID you must first activate the _Enable User ID Tracking_ setting in the Magento admin panel.

I think it works pretty well so far, except when signing out. The [documentation](https://piwik.org/docs/user-id/#how-requests-with-a-user-id-are-tracked) states that:
> If then visitor logs out then the visitor has no User ID set any more and a new visit will be created on the page view right after logging out.

This seems not to be the case. At least in my tests with Piwik 3.0.1, the subsequent page views after logging out are still attributed to the logged-in user, even though the user ID is no longer being sent. I'm not sure how big of an issue that is though, as the `visit_standard_length` Piwik setting will eventually create a new visit if the browsing is idle for long enough. It looks like there is [an open bug report](https://github.com/piwik/piwik/issues/7556) for this issue so maybe this is good enough for now?

Please let me know what you think and if this feature works as you expected.

Cheers,
H

**Comment by souzavitor** [comment]
I've seen the update you made and It's working fine, thanks.

But I think it is better to use the customer email instead of the customer id. Or maybe it could be configured.

**Comment by henkelund** [comment]
If you want to use the customer email you can change preference for the user ID provider in another module's `etc/di.xml`:
```xml
<preference for="Henhed\Piwik\Model\UserId\ProviderInterface" type="Foo\Bar\UserId" />
```
And implement the interface like so:
```php
<?php

namespace Foo\Bar;

class UserId implements \Henhed\Piwik\Model\UserId\ProviderInterface
{

    protected $_customerRepository;

    public function __construct(
        \Magento\Customer\Api\CustomerRepositoryInterface $customerRepository
    ) {
        $this->_customerRepository = $customerRepository;
    }

    public function getUserId($customerId)
    {
        try {
            return $this->_customerRepository->getById($customerId)->getEmail();
        } catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
            return false;
        }
    }
}
```
Note: You might have to add `Henhed_Piwik` to your module's `<sequence>` and run `setup:upgrade` for the preference to take effect.

There are a few reasons why I chose to implemented it this way:
- The customer entity ID is the most persistent identifier to use by default. A customer can change their email at any point which, I imagine, would confuse Piwik's visitor tracking.
- A configuration setting for choosing either customer ID or email would be convenient, but it would also give admins the freedom to switch back and forth between the two, effectively changing the User ID of every single customer.
- The entity ID is shorter than an email address which reduces the risk of hitting request size limits and requires less storage capacity in Piwik.
- By providing an interface, the User ID is not limited to Magento's standard identifiers. Any custom logic or formatting can be applied. For instance, a merchant could implement it to use an ID from some external source, like a CRM, ERP or loyalty system.

I realize that it's a bit inconvenient but I think this approach provides more reliable data by default and is (with some effort) more flexible.

Do you agree with my point of view? If not, what makes email the better choice in you opinion?

**Comment by souzavitor** [comment]
I agree with you that makes sense to use the customer ID to track the user visits, but I think it's sometimes  good to have the option to use another unique user information, such as email or username. I think that way it makes easier to identify the user in the Piwik reports.

In the Piwik documentation (http://piwik.org/docs/user-id/) we can see some good possibilities to use to track the user visit.

**Comment by henkelund** [comment]
Ok, I've made an update to the same branch (`user-id`) that you're welcome to try out. The _Enable User ID Tracking_ config option now lets you choose between entity ID and e-mail for user ID tracking.

It's still possible (but not required) to customize the user ID programmatically by adding more implementations of the user ID provider interface to `Henhed\Piwik\UserId\Provider\Pool` in your `etc/di.xml` file.

Please let me know if this update works well for you.

**Comment by henkelund** [comment]
@souzavitor I'd like to include this feature in the next release. Have you had a chance to test my last update yet?

**Comment by souzavitor** [comment]
It works well for me, thank you very much!

**Comment by henkelund** [comment]
@souzavitor Great!

I've removed the `user-id` branch. Please install version 1.3.0 instead (`composer require henhed/module-piwik:v1.3.0`)
