### ISSUE TITLE
No data has been recorded yet

### ISSUE THREAD

**Issue by surajiiitm** [fnogatz/magento2-matomo#16]
No data has been recorded yet, as i am using magento extension for piwik for JavaScript tracking code but no result is coming for visit log and and order. I have checked date and all but no visit log is coming.

**Comment by henkelund** [comment]
Hi,

Have you enabled the module and made all necessary configuration settings?
Have you checked if the Piwik javascript is successfully loaded in the frontend?

**Comment by surajiiitm** [comment]
yes , I have enabled module and piwik javascript is successfully loaded in frontend and showing in the UI also but still no data is being tracked.

**Comment by henkelund** [comment]
Do you get any JS console error messages?

You should see a request looking something like this:
![henhed_piwik_16-1](https://user-images.githubusercontent.com/834660/29428090-3bebeb62-838c-11e7-8a58-6ab1b82f387b.png)
If you do, all is probably well on the Magento side. Make sure you see a `200 OK` response and that the `idsite` variable is correct.

**Comment by henkelund** [comment]
@surajiiitm Have you made any progress on this issue?
