### ISSUE TITLE
PHP 7.1

### ISSUE THREAD

**Issue by cytracon** [fnogatz/magento2-matomo#18]
Hi there, any chance to make it work with PHP 7.1? Many thanks, Bernard

**Comment by henkelund** [comment]
Hi Bernard,

I don't think there are any issues with PHP 7.1 aside from the `composer.json` requirement (let me know if I'm wrong).

Could you please try out the `1.3.1` branch and let me know if that works for you:

```sh
composer require henhed/module-piwik:1.3.1.x-dev
```

**Comment by AgentGod** [comment]
I have just installed module-piwik:1.3.1.x-dev on magento 2.2 with php 7.1 and seems works well.

**Comment by henkelund** [comment]
Great!

Iv'e tagged a new release, [v1.3.1](https://github.com/henkelund/magento2-henhed-piwik/releases/tag/v1.3.1).

```sh
composer require henhed/module-piwik:v1.3.1
```

Thank you for your feedback!

**Comment by cytracon** [comment]
Hi Hendrik, works perfectly, many thanks!
