### ISSUE TITLE
Add dependencies on magento core modules

### ISSUE THREAD

**Issue by ihor-sviziev** [fnogatz/magento2-matomo#20]
I don't see in composer.json require section any magento modules are required for correct work if this module.

There is dependencies to:
- [magento framework](https://github.com/henkelund/magento2-henhed-piwik/blob/master/Block/Piwik.php#L27)
- [magento checkout](https://github.com/henkelund/magento2-henhed-piwik/blob/master/CustomerData/Checkout/CartPlugin.php#L67)
- [magento customer](https://github.com/henkelund/magento2-henhed-piwik/blob/master/CustomerData/Customer/CustomerPlugin.php#L59)
- [magento store](https://github.com/henkelund/magento2-henhed-piwik/blob/master/Helper/Data.php#L57)
- [magento quote](https://github.com/henkelund/magento2-henhed-piwik/blob/master/Helper/Tracker.php#L24)
- [magento sales](https://github.com/henkelund/magento2-henhed-piwik/blob/master/Observer/CheckoutSuccessObserver.php#L64)
- [magento search](https://github.com/henkelund/magento2-henhed-piwik/blob/master/Observer/SearchResultObserver.php#L72)

If any of these modules will have backward incompatible version that is not tested with this module - it might brake this module. In order to fix it we need to add dependencies to supported module versions.

Also it's not clear, do this module supports Magento 2.2.2?

**Comment by henkelund** [comment]
Hi,

I've added the module dependencies i could find in the [2.0.0](https://github.com/henkelund/magento2-henhed-piwik/commit/fb18ea423dbda7e5f8312a9488815f5a9295d079) branch, starting from the versions shipped with Magento 2.2.0.

The module works with 2.2.2, as far as I have tested, but Magento upgraded the bundled version of PHPUnit so all unit tests have to be rewritten. 

When all test are rewritten, the plan is to release a 2.0 version which drops support for PHP < 7 and Magento < 2.2.
