### ISSUE TITLE
Travis builds fails due to missing environment variables

### ISSUE THREAD

**Issue by ihor-sviziev** [fnogatz/magento2-matomo#22]
Currently builds on travis are failing due to missing env. variable M2_REPO_USERNAME.

Example: https://travis-ci.org/henkelund/magento2-henhed-piwik/jobs/324532521
Could you fix it?

**Comment by henkelund** [comment]
Hi,

The variable is missing because it's a secret variable and Travis considers forks to be "unsafe" (you can read more about that [here](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions)). I'm not aware of any workarounds for this ATM.
