### ISSUE TITLE
Installed and enabled the plugin but it can't enable anything in magento 2 admin page

### ISSUE THREAD

**Issue by gawainchin** [fnogatz/magento2-matomo#25]
Hi. Thank you for making this plugin. 
I have followed the installation guide and installed henhed-piwik 1.3.1 for magento2.2.
I can see the Piwik API session under admin dashboard but there aren't anything to select as shown in the picture. 

![magento2](https://user-images.githubusercontent.com/36292612/36016677-26a06b68-0daf-11e8-9ca6-8a7dc480c2d8.PNG)

Is there anything could make this happen? 

I am currently placing the plugin in magento2/app/code/henhed/magento2-henhed-piwik

Thanks in advance!

**Comment by henkelund** [comment]
Hi,

For Magento 2.2 you should use the `2.0` version, not `1.3`. The module should be placed in `app/code/Henhed/Piwik` if you're installing it manually.

If you are familiar with using a command line interface, I would like to recommend using [Composer](https://getcomposer.org/) to install modules instead. Composer will know where to put the module and also tries to figure out which version you should use.

Hope this helps,
Cheers

**Comment by gawainchin** [comment]
It helps and the plugin works like a charm. 
Thank you very much!
