### ISSUE TITLE
No transfer of shopping cart contents

### ISSUE THREAD

**Issue by KlausGw** [fnogatz/magento2-matomo#26]
Hello,

Magento 2.2.2
Henhed_Piwik
Matomo 3.3.0

Tracking works until the shopping cart, but the checkout does not transfer the data and the shopping cart is empty.
It's not always like that, sometimes it works.
Does anyone know the problem and has a solution?

Best regards
Klaus

**Comment by henkelund** [comment]
Hi Klaus,

It's difficult to guess what your problem might be without more information. Do you know how to reproduce the issue? Do you get any browser console messages?

Also, which version of the module are you using?

Cheers,
Henrik
