### ISSUE TITLE
The method setTrackerUrl is registered more than once in "_paq" variable 

### ISSUE THREAD

**Issue by igortregub** [fnogatz/magento2-matomo#28]
I've faced the same issue as It was described in https://github.com/henkelund/magento2-henhed-piwik/issues/15

### Preconditions
1. Magento 2.2.3
2. henhed/module-piwik 2.0.0
3. Google Chrome

### Steps to reproduce
1. open dev console
1. add some product to the Shopping Cart
2. go to the checkout page
3. see errors on the dev console

### Expected result

1. there mustn't be any errors on the dev console

### Actual result

1. there are js errors:
![piwik-js-console-error](https://user-images.githubusercontent.com/6198012/37776520-23c1db2a-2dee-11e8-833f-6aa147ef5cc6.png)

------ 
if this issue you cannot reproduce, refresh your checkout page few times

It's happening because on the checkout page code 
https://github.com/henkelund/magento2-henhed-piwik/blob/master/view/frontend/templates/piwik.phtml#L36-L49 
runs in paralel with code 
https://github.com/henkelund/magento2-henhed-piwik/blob/master/view/frontend/web/js/tracker.js#L298-L303
 as result tracker.js tries to inject piwik.js file second time.

My PR adds checking if such script already exists on this page: https://github.com/henkelund/magento2-henhed-piwik/pull/27

**Comment by henkelund** [comment]
Hi @igortregub!

I tried, but I couldn't reproduce this issue in my environment. But I can see how it could happen so I've merged your PR and released [v2.0.1](https://github.com/henkelund/magento2-henhed-piwik/releases/tag/v2.0.1).

Thanks for your contribution

**Comment by igortregub** [comment]
Thank you :)
