### ISSUE TITLE
Magento 2.3. compatibility

### ISSUE THREAD

**Issue by afavata** [fnogatz/magento2-matomo#33]
Hi 

is current Piwik/Matomo extension compatible with magento 2.3.0???
thanks

**Comment by Kesquom** [comment]
Hi

I just tried to upgrade from Magento 2.2.6 to 2.3 and composer wouldn't let me because of this extension. So for now some dependency restrictions seem to prevent an upgrade.

**Comment by AgentGod** [comment]
it will be great such module to be updated

**Comment by Boumii** [comment]
*push*
to see support for Magento2  v2.3.1 and PHP 7.2 would be awesome

**Comment by afavata** [comment]
absolutely agreed….

need full support for  Magento2 v2.3.1 and PHP 7.2 …. please

**Comment by JesseEnd** [comment]
I removed this extension from composer and uploaded the zip files to app/code, and so far it seems to be working fine in Magento 2.3.1

**Comment by henkelund** [comment]
Hi people. I've made a release (v2.0.3) with support for Magento 2.3 and PHP 7.2. Sorry for taking such a long time to do it but I currently have no personal use for this module so it's near the bottom of my priority list.
