### ISSUE TITLE
Customization Tracking

### ISSUE THREAD

**Issue by shekharS7** [fnogatz/magento2-matomo#34]
I had one event payment_form_success (custom). That event is executed on successful payment of order. I put logger on  it and its working. There I want to tracking success payment event track. I used observer for this event. There I put  this code.           
$this->_piwikTracker->trackEvent('payment', 'Payment for Order Id', '576');
$this->_piwikTracker object is load in construct. 
Its still not tracking. I didn't find why its not tracking.

**Comment by amenk** [comment]
is this still an issue?

**Comment by shekharS7** [comment]
No.
