### ISSUE TITLE
Module not working with Magento 2.4.0

### ISSUE THREAD

**Issue by kamzata** [fnogatz/magento2-matomo#46]
Just tried to install it using composer on Magento 2.4.0 and I received this error message:

```
[InvalidArgumentException]
Package henhed/module-piwik at version  has a PHP requirement incompatible with your PHP version (7.4.3)
```

Any chances to make this working on it?

**Comment by fnogatz** [comment]
Related PR: https://github.com/henkelund/magento2-henhed-piwik/pull/45

**Comment by ferdiusa** [comment]
Also note: you need to update an additional composer requirement for Magento 2.4.x support:
"magento/framework": "~101.0|~102.0**|~103.0**",

**Comment by fnogatz** [comment]
FYI: Some weeks ago, I created the fork [fnogatz/magento2-matomo](https://github.com/fnogatz/magento2-matomo), which can be installed on Magento 2.4 using composer via `composer require chessio/module-matomo`.

**Comment by fnogatz** [comment]
Hey @kamzata, thank you again for reporting this issue. In the meantime, the original module `Henhed_Piwik` has been abandoned, so please switch to this `Chessio_Matomo` for compatibility with Magento 2.4 and PHP 7.4.

**Comment by kamzata** [comment]
> Hey @kamzata, thank you again for reporting this issue. In the meantime, the original module `Henhed_Piwik` has been abandoned, so please switch to this `Chessio_Matomo` for compatibility with Magento 2.4 and PHP 7.4.

Hey @fnogatz, just switched. I hope you maintain it for longer. Thanks
