### ISSUE TITLE
PHP 7.4 support open pull request needs merged.

### ISSUE THREAD

**Issue by Jieiku** [fnogatz/magento2-matomo#48]
I tested this on my install by manually editing composer.json and making the edit, it works perfectly.

Merging the pull request will allow people to install using composer, which is what I originally tried before cloning the repository and manually editing the composer file.

open pull request:

https://github.com/henkelund/magento2-henhed-piwik/pull/45

**Comment by amenk** [comment]
It's merged - I believe this can be closed :)
