### ISSUE TITLE
Matomo for M2 extension is not compatible with M2.4.4  released April 2022

### ISSUE THREAD

**Issue by n2diving-net** [fnogatz/magento2-matomo#60]
More specifically it appears to use php 7 syntax that is deprecated in the php 8 version required by Magento 2.4.4 release. 

$ php bin/magento --version
Magento CLI 2.4.4
$ php -v
PHP 8.1.4 (cli) (built: Apr 12 2022 11:12:25) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.4, Copyright (c) Zend Technologies
$ composer require chessio/module-matomo

  [InvalidArgumentException]
  Package chessio/module-matomo has requirements incompatible with your PHP version, PHP extensions and Composer version:
    - chessio/module-matomo v2.1.3 requires php ~7.0.0|~7.1.0|~7.2.0|~7.3.0|~7.4.0 which does not match your installed version 8.1.4.

**Comment by malou72** [comment]
Hello,

First, Thanks for the work made.

How have you bypass this issue ?
What's the solution ?

**Comment by kamzata** [comment]
+1

**Comment by candreas-isp** [comment]
+1

**Comment by zamu87** [comment]
Resolved in #62

**Comment by fnogatz** [comment]
Thank you all for pointing this out. Supported for PHP 8.1 and 8.2 has now been added in [v2.1.4](https://github.com/fnogatz/magento2-matomo/releases/tag/v2.1.4) thanks to @zamu87 (#62).
